# Generated by Django 5.2.7 on 2025-11-04 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("contacto", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Computadora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modelo", models.CharField(max_length=100)),
                ("procesador", models.CharField(max_length=100)),
                ("ram", models.CharField(max_length=50)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="imagenes/"),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="computadoras.proveedor",
                    ),
                ),
            ],
        ),
    ]
